import { Activity } from "lucide-react";
import { AdminCard, AdminPageHeader } from "@/components/admin/AdminShell";
import { getAdminContext } from "@/lib/admin-server";

export const dynamic = "force-dynamic";
const date = new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" });

export default async function AdminActivityPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams; const admin = await getAdminContext(); const db = admin.supabase as any; const action = typeof params.action === "string" ? params.action.trim().slice(0, 100).replace(/[,%()]/g, "") : ""; const result = typeof params.result === "string" ? params.result : "all"; const actor = typeof params.actor === "string" && /^[0-9a-f-]{36}$/i.test(params.actor) ? params.actor : ""; const target = typeof params.target === "string" ? params.target.trim().slice(0, 200) : ""; const from = typeof params.from === "string" && /^\d{4}-\d{2}-\d{2}$/.test(params.from) ? params.from : ""; const to = typeof params.to === "string" && /^\d{4}-\d{2}-\d{2}$/.test(params.to) ? params.to : "";
  let query = db.from("admin_audit_log").select("id,actor_id,actor_role,action,target_type,target_id,summary,result,correlation_id,created_at").order("created_at", { ascending: false }).limit(100); if (action) query = query.ilike("action", `%${action}%`); if (["success","denied","failed"].includes(result)) query = query.eq("result", result); if (actor) query = query.eq("actor_id", actor); if (target) query = query.eq("target_id", target); if (from) query = query.gte("created_at", new Date(from).toISOString()); if (to) query = query.lte("created_at", new Date(`${to}T23:59:59.999`).toISOString()); const { data: events = [] } = await query;
  const actors = [...new Set(events.map((event: any) => event.actor_id).filter(Boolean))] as string[]; const { data: profiles = [] } = actors.length ? await db.from("profiles").select("id,email,display_name").in("id", actors) : { data: [] }; const profileMap = new Map(profiles.map((profile: any) => [profile.id, profile]));
  return <><AdminPageHeader title="Activity" description="Append-only records for sensitive staff actions. Passwords, tokens, and message bodies are never logged." /><AdminCard><form className="grid gap-3 md:grid-cols-3 xl:grid-cols-6"><label className="form-label">Actor ID<input className="form-control" name="actor" defaultValue={actor} /></label><label className="form-label">Action contains<input className="form-control" name="action" defaultValue={action} /></label><label className="form-label">Target ID<input className="form-control" name="target" defaultValue={target} /></label><label className="form-label">From<input className="form-control" name="from" type="date" defaultValue={from} /></label><label className="form-label">To<input className="form-control" name="to" type="date" defaultValue={to} /></label><label className="form-label">Result<select className="form-control" name="result" defaultValue={result}><option value="all">All results</option><option value="success">Success</option><option value="denied">Denied</option><option value="failed">Failed</option></select></label><button className="btn-primary md:col-span-3 xl:col-span-6">Filter activity</button></form></AdminCard><div className="mt-5 grid gap-3">{events.map((event: any) => { const actorProfile = profileMap.get(event.actor_id) as any; return <AdminCard key={event.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-black text-foreground">{event.action}</p><p className="mt-1 text-sm text-muted">{event.summary}</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${event.result === "success" ? "bg-emerald-100 text-emerald-950" : "bg-red-100 text-red-950"}`}>{event.result}</span></div><dl className="mt-4 grid gap-2 text-xs sm:grid-cols-4"><div><dt className="type-caption">Actor</dt><dd>{actorProfile?.display_name || actorProfile?.email || "Deleted staff account"} ({event.actor_role})</dd></div><div><dt className="type-caption">Target</dt><dd>{event.target_type}: {event.target_id || "none"}</dd></div><div><dt className="type-caption">Correlation</dt><dd className="break-all">{event.correlation_id}</dd></div><div><dt className="type-caption">Time</dt><dd>{date.format(new Date(event.created_at))}</dd></div></dl></AdminCard>; })}{!events.length ? <AdminCard><div className="py-8 text-center"><Activity className="mx-auto h-8 w-8 text-subtle" /><p className="mt-2 font-black">No audited activity matches these filters.</p></div></AdminCard> : null}</div></>;
}
