import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminCard, AdminPageHeader } from "@/components/admin/AdminShell";
import { SupportReplyForm, SupportStatusForm } from "@/components/support/SupportForms";
import { getAdminContext } from "@/lib/admin-server";
import { formatSupportCategory, formatSupportStatus } from "@/lib/support";

export const dynamic = "force-dynamic";
const date = new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" });

export default async function AdminTicketPage({ params }: { params: Promise<{ ticketId: string }> }) {
  const { ticketId } = await params; const admin = await getAdminContext(); const db = admin.supabase as any;
  const { data: ticket } = await db.from("support_tickets").select("id,ticket_number,user_id,subject,category,status,priority,page_url,diagnostics_consent,diagnostics,assigned_to,created_at,updated_at,resolved_at").eq("id", ticketId).maybeSingle(); if (!ticket) notFound();
  const [{ data: messages = [] }, { data: notes = [] }, { data: user }] = await Promise.all([db.from("support_messages").select("id,author_id,author_kind,body,created_at").eq("ticket_id", ticketId).order("created_at"), db.from("support_staff_notes").select("id,author_id,body,created_at").eq("ticket_id", ticketId).order("created_at"), db.from("profiles").select("id,email,display_name,account_status").eq("id", ticket.user_id).maybeSingle()]);
  const authorIds = [...new Set([...messages, ...notes].map((item: any) => item.author_id).concat(ticket.assigned_to).filter(Boolean))]; const { data: authors = [] } = authorIds.length ? await db.from("profiles").select("id,display_name,email").in("id", authorIds) : { data: [] }; const authorMap = new Map(authors.map((author: any) => [author.id, author])); const assignee = authorMap.get(ticket.assigned_to) as any;
  return <><AdminPageHeader title={`Ticket #${ticket.ticket_number}`} description={ticket.subject} actions={<><Link className="btn-outline" href={`/admin/users/${ticket.user_id}`}>View user</Link><Link className="btn-outline" href="/admin/support">Back to queue</Link></>} />
    <div className="grid gap-6 xl:grid-cols-[1fr_380px]"><div className="grid gap-6"><AdminCard><h2 className="type-card">Conversation</h2><div className="mt-4 grid gap-3">{messages.map((item: any) => { const author = authorMap.get(item.author_id) as any; return <article key={item.id} className={`rounded-lg border p-4 ${item.author_kind === "staff" ? "border-blue-300 bg-blue-50 text-slate-950" : "border-border bg-surface-secondary"}`}><div className="flex justify-between gap-3 text-xs"><strong>{author?.display_name || author?.email || item.author_kind}</strong><time>{date.format(new Date(item.created_at))}</time></div><p className="mt-2 whitespace-pre-wrap text-sm">{item.body}</p></article>; })}</div><div className="mt-6 border-t border-border pt-5"><SupportReplyForm ticketId={ticketId} admin /></div></AdminCard>
    <AdminCard><h2 className="type-card">Private staff notes</h2><p className="mt-1 text-sm text-muted">Never visible to the learner. Notes are append-only.</p><div className="mt-4 grid gap-3">{notes.map((note: any) => { const author = authorMap.get(note.author_id) as any; return <article key={note.id} className="rounded-lg border border-amber-300 bg-amber-50 p-4 text-amber-950"><div className="flex justify-between text-xs"><strong>{author?.display_name || author?.email || "Staff"}</strong><time>{date.format(new Date(note.created_at))}</time></div><p className="mt-2 whitespace-pre-wrap text-sm">{note.body}</p></article>; })}{!notes.length ? <p className="text-sm text-muted">No private notes.</p> : null}</div><div className="mt-5"><SupportReplyForm ticketId={ticketId} admin note /></div></AdminCard></div>
    <aside className="grid content-start gap-6"><AdminCard><h2 className="type-card">Ticket status</h2><p className="mt-2 font-black">{formatSupportStatus(ticket.status)}</p><p className="mt-1 text-sm text-muted">Assigned to {assignee?.display_name || assignee?.email || "no one"}</p><div className="mt-4"><SupportStatusForm ticketId={ticketId} status={ticket.status} assigned={Boolean(ticket.assigned_to)} /></div></AdminCard><AdminCard><h2 className="type-card">Context</h2><dl className="mt-4 grid gap-3 text-sm"><div><dt className="type-caption">Learner</dt><dd className="font-bold">{user?.display_name || user?.email}</dd></div><div><dt className="type-caption">Category</dt><dd className="font-bold">{formatSupportCategory(ticket.category)}</dd></div><div><dt className="type-caption">Priority</dt><dd className="font-bold capitalize">{ticket.priority}</dd></div><div><dt className="type-caption">Created</dt><dd className="font-bold">{date.format(new Date(ticket.created_at))}</dd></div><div><dt className="type-caption">Updated</dt><dd className="font-bold">{date.format(new Date(ticket.updated_at))}</dd></div><div><dt className="type-caption">Page</dt><dd className="break-all font-bold">{ticket.page_url || "Not supplied"}</dd></div><div><dt className="type-caption">Diagnostics consent</dt><dd className="font-bold">{ticket.diagnostics_consent ? "Yes" : "No"}</dd></div></dl></AdminCard></aside></div></>;
}
