import Link from "next/link";
import { notFound } from "next/navigation";
import { AccountAvatar } from "@/components/AccountAvatar";
import { CopyButton } from "@/components/CopyButton";
import { AdminCard, AdminPageHeader } from "@/components/admin/AdminShell";
import { AdminUserActions } from "@/components/admin/AdminUserActions";
import { UserStaffNoteForm } from "@/components/admin/UserStaffNoteForm";
import { canManageAccount } from "@/lib/admin-security";
import { getAdminContext } from "@/lib/admin-server";
import { resolveAccountIdentity } from "@/lib/identity";
import { formatSupportStatus } from "@/lib/support";

export const dynamic = "force-dynamic";
const timestamp = new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" });

export default async function AdminUserDetail({ params }: { params: Promise<{ userId: string }> }) {
  const { userId } = await params; const admin = await getAdminContext(); if (!admin.service) notFound(); const db = admin.service as any;
  const [profileResult, authResult, attempts, progress, skills, tickets, history, userNotes, languages, recentAttempts] = await Promise.all([
    db.from("profiles").select("id,email,display_name,avatar_url,role,onboarding_completed,account_status,account_status_reason,account_status_changed_at,preferred_language,experience_level,learning_goal,created_at").eq("id", userId).maybeSingle(),
    admin.service.auth.admin.getUserById(userId),
    db.from("attempts").select("id", { count: "exact", head: true }).eq("user_id", userId),
    db.from("lesson_progress").select("id", { count: "exact", head: true }).eq("user_id", userId).eq("status", "completed"),
    db.from("skill_scores").select("language_slug,topic,mastery").eq("user_id", userId).order("mastery", { ascending: false }).limit(8),
    db.from("support_tickets").select("id,ticket_number,subject,status,updated_at").eq("user_id", userId).order("updated_at", { ascending: false }).limit(10),
    db.from("account_status_history").select("id,previous_status,new_status,reason,created_at").eq("user_id", userId).order("created_at", { ascending: false }).limit(10),
    db.from("user_staff_notes").select("id,author_id,body,created_at").eq("user_id", userId).order("created_at", { ascending: false }).limit(20),
    db.from("language_experience").select("language_slug,experience_level").eq("user_id", userId).order("created_at", { ascending: false }),
    db.from("attempts").select("id,attempt_type,language_slug,score,started_at,completed_at").eq("user_id", userId).order("started_at", { ascending: false }).limit(5)
  ]);
  const profile = profileResult.data; const authUser = authResult.data.user; if (!profile || !authUser) notFound(); const identity = resolveAccountIdentity(authUser, profile);
  const manageable = canManageAccount({ actorId: admin.user!.id, actorRole: admin.role, targetId: userId, targetRole: profile.role });
  return <><AdminPageHeader title={identity.label} description="Account identity, learning signals, support history, and controlled recovery actions." actions={<><CopyButton value={userId} label="Copy user ID" /><Link className="btn-outline" href="/admin/users">Back to users</Link></>} />
    <div className="grid gap-6 xl:grid-cols-[1fr_380px]"><div className="grid gap-6"><AdminCard><div className="flex items-center gap-4"><AccountAvatar identity={identity} size="lg" decorative /><div><h2 className="type-section">{identity.label}</h2><p className="text-muted">{identity.email}</p><code className="text-xs text-subtle">{userId}</code></div></div><dl className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["Role", profile.role],["Status", profile.account_status],["Providers", identity.providers.join(", ") || "email"],["Email confirmed", authUser.email_confirmed_at ? "Yes" : "No"],["Onboarding", profile.onboarding_completed ? "Complete" : "Not complete"],["Created", timestamp.format(new Date(profile.created_at))],["Last sign-in", authUser.last_sign_in_at ? timestamp.format(new Date(authUser.last_sign_in_at)) : "Never"],["Preferred language", profile.preferred_language || "Not set"],["Learning goal", profile.learning_goal || "Not set"]].map(([label,value]) => <div key={label}><dt className="type-caption">{label}</dt><dd className="mt-1 font-bold text-foreground">{value}</dd></div>)}</dl></AdminCard>
    <AdminCard><h2 className="type-card">Learning activity</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-lg bg-surface-secondary p-4"><p className="type-caption">Attempts</p><p className="mt-1 text-2xl font-black">{attempts.count ?? 0}</p></div><div className="rounded-lg bg-surface-secondary p-4"><p className="type-caption">Lessons completed</p><p className="mt-1 text-2xl font-black">{progress.count ?? 0}</p></div><div className="rounded-lg bg-surface-secondary p-4"><p className="type-caption">Skill topics</p><p className="mt-1 text-2xl font-black">{skills.data?.length ?? 0}</p></div></div>{skills.data?.length ? <ul className="mt-4 grid gap-2">{skills.data.map((skill: any) => <li key={`${skill.language_slug}-${skill.topic}`} className="flex justify-between rounded-lg border border-border p-3"><span>{skill.language_slug} · {skill.topic}</span><strong>{Math.round(Number(skill.mastery))}%</strong></li>)}</ul> : <p className="mt-4 text-sm text-muted">No recorded skill scores yet.</p>}</AdminCard>
    <AdminCard><h2 className="type-card">Support history</h2>{tickets.data?.length ? <ul className="mt-4 divide-y divide-border">{tickets.data.map((ticket: any) => <li key={ticket.id} className="flex items-center justify-between gap-3 py-3"><div><p className="font-bold">#{ticket.ticket_number} {ticket.subject}</p><p className="text-sm text-muted">{formatSupportStatus(ticket.status)}</p></div><Link className="btn-outline" href={`/admin/support/${ticket.id}`}>Open</Link></li>)}</ul> : <p className="mt-4 text-sm text-muted">No support tickets.</p>}</AdminCard>
    <AdminCard><h2 className="type-card">Account status history</h2>{history.data?.length ? <ul className="mt-4 divide-y divide-border">{history.data.map((event: any) => <li key={event.id} className="py-3"><p className="font-bold">{event.previous_status} → {event.new_status}</p><p className="text-sm text-muted">{event.reason}</p><time className="text-xs text-subtle">{timestamp.format(new Date(event.created_at))}</time></li>)}</ul> : <p className="mt-4 text-sm text-muted">No account-status changes.</p>}</AdminCard></div>
    <aside className="grid content-start gap-6"><AdminCard><h2 className="type-card">Learning profile</h2><p className="mt-2 text-sm text-muted">{languages.data?.length ? languages.data.map((item: any) => `${item.language_slug} (${item.experience_level})`).join(", ") : "No selected language experience."}</p>{recentAttempts.data?.length ? <ul className="mt-4 grid gap-2 text-sm">{recentAttempts.data.map((attempt: any) => <li key={attempt.id} className="rounded-lg bg-surface-secondary p-3"><strong>{attempt.attempt_type}</strong><span className="block text-muted">{attempt.language_slug || "General"} · {attempt.score ?? "No score"} · {timestamp.format(new Date(attempt.started_at))}</span></li>)}</ul> : <p className="mt-3 text-sm text-muted">No recent attempts.</p>}</AdminCard><AdminCard><h2 className="type-card">Private staff notes</h2><p className="mt-1 text-sm text-muted">Append-only and never shown to the learner.</p>{userNotes.data?.length ? <ul className="mt-4 grid gap-3">{userNotes.data.map((note: any) => <li key={note.id} className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950"><p className="whitespace-pre-wrap">{note.body}</p><p className="mt-2 text-xs">Author {note.author_id || "deleted staff"} · {timestamp.format(new Date(note.created_at))}</p></li>)}</ul> : <p className="mt-3 text-sm text-muted">No private account notes.</p>}{manageable ? <UserStaffNoteForm userId={userId} /> : null}</AdminCard><AdminCard><h2 className="type-card">Account actions</h2><p className="mt-2 mb-5 text-sm text-muted">These actions never reveal passwords, tokens, or reset links. Every attempt is audited.</p><AdminUserActions userId={userId} status={profile.account_status} manageable={manageable} emailConfirmed={Boolean(authUser.email_confirmed_at)} /></AdminCard></aside></div></>;
}
